import { colours } from "./Colours.js"
import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  kuukausiTeksti: {
    marginTop: 30,
    marginBottom: 24,
    fontSize: 20,
  },
  etusivu: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  hCenter: {
    flex: 1,
    alignItems: "center",
  },
  arrowsFrontpage: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    bottom: 50,
    paddingHorizontal: 50,
},
  buttonFrontpage: {
    backgroundColor: colours.button,
    width: 130,
    height: 70,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 6,
},
  floatingControls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: 30,
    justifyContent: 'center',
},
  popup: {
    backgroundColor: colours.background,
    borderRadius: 12,
    padding: 24,
    width: '80%',
  },
  popupOverlay: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    position: 'absolute',
    backgroundColor: 'rgba(0,0,0,0.0)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginContainer: {
    flex: 1,
    backgroundColor: colours.background,
    padding: 20,
    justifyContent: "center",
  },
  container: {
    flex: 1,
    backgroundColor: colours.background,
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: colours.textPrimary,
    marginBottom: 20,
  },
  input: {
    backgroundColor: colours.card,
    color: colours.blackText,
    padding: 14,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: colours.borderColour,
  },
  button: {
    backgroundColor: colours.button,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
  },
  buttonText: {
    color: colours.blackText,
    fontSize: 16,
    fontWeight: "600",
  },
  card: {
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: colours.card,
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  name: {
    fontSize: 18,
    fontWeight: "bold",
    color: colours.blackText,
    marginBottom: 5,
  },
  description: {
    fontSize: 14,
    color: colours.textSecondary,
    marginBottom: 5,
  },
  error: {
    color: colours.error,
    padding: 5,
  },
  addButton: {
    backgroundColor: colours.button,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
  },
  devButton: {
    backgroundColor: colours.button,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 20,
  },
  addButtonText: {
    color: colours.blackText,
    fontSize: 16,
    fontWeight: "600",
  },
  empty: {
    textAlign: "center",
    marginTop: 40,
    color: colours.textSecondary,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  hamburgerOverlay: {
    flex: 1,
  },
  hamburgerContainer: {
    position: 'absolute',
    top: 60,
    left: 10,
    backgroundColor: colours.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colours.borderColour,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    minWidth: 200,
    overflow: 'hidden',
  },
  hamburgerItem: {
    padding: 16,
    backgroundColor: colours.card,
  },
  hamburgerSeparator: {
    height: 1,
    backgroundColor: colours.borderColour,
  },
  hamburgerItemText: {
    fontSize: 16,
    color: colours.blackText,
  },
  hamburgerItemTextDanger: {
    fontSize: 16,
    color: colours.error,
  },
})
